[project]
name = "kada-commute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "google-auth>=2.43.0",
    "gspread>=6.2.1",
    "uvicorn>=0.40.0",
]
